apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-service
spec:
  selector:
    app: go-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-modifier-service
spec:
  selector:
    app: metrics-modifier-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: ClusterIP